import SavingsCard from "@/components/audit/savings-card";

import RecommendationCard from "@/components/audit/recommendation-card";

import SavingsChart from "@/components/charts/savings-chart";

import AuditSummary from "@/components/audit/audit-summary";
import ShareButton from "@/components/audit/share-button";

interface AuditPageProps {
  params: {
    id: string;
  };
}

async function getAudit(id: string) {
  try {
    const { supabase } = await import("@/lib/db/supabase");
    
    const { data, error } = await supabase
      .from("audits")
      .select("*")
      .eq("id", id)
      .single();

    if (error || !data) {
      return null;
    }

    return {
      success: true,
      audit: data,
    };
  } catch (error) {
    console.error("Error fetching audit:", error);
    return null;
  }
}

export async function generateMetadata({
  params,
}: AuditPageProps) {
  const resolvedParams = await params;
  const data = await getAudit(resolvedParams.id);

  if (!data?.success) {
    return {
      title: "Audit Not Found",
    };
  }

  const audit = data.audit;

  return {
    title: `Save $${audit.total_annual_savings}/year on AI tools`,

    description:
      "AI infrastructure optimization report generated by Yukthi.",

    openGraph: {
      title: `Save $${audit.total_annual_savings}/year on AI tools`,

      description:
        "AI infrastructure optimization report.",

      type: "website",
    },
  };
}

export default async function AuditPage({
  params,
}: AuditPageProps) {
  const resolvedParams = await params;
  const data = await getAudit(resolvedParams.id);

  if (!data?.success) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-black text-white">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4">Audit Report Not Found</h1>
          <p className="text-zinc-400">
            The audit report you're looking for doesn't exist or has been removed.
          </p>
        </div>
      </main>
    );
  }

  const audit = data.audit;

  const optimizedSpend =
    audit.total_monthly_spend -
    audit.total_monthly_savings;

  const optimizationScore = Math.max(
    0,
    Math.min(
      100,
      Math.round(
        (audit.total_monthly_savings /
          audit.total_monthly_spend) *
          100
      )
    )
  );

  return (
    <main className="relative min-h-screen overflow-hidden bg-black text-white">
      <section className="relative z-10 mx-auto max-w-7xl px-6 py-16">
        <div className="flex items-start justify-between gap-6 mb-12">
          <div>
            <p className="text-sm font-semibold uppercase tracking-widest text-blue-400">
              Shared Audit Report
            </p>

            <h1 className="mt-4 text-5xl font-bold tracking-tight text-white md:text-6xl">
              AI Infrastructure Optimization
            </h1>

            <p className="mt-6 max-w-2xl text-lg leading-relaxed text-zinc-300">
              This shared audit report contains AI infrastructure cost optimization recommendations powered by deterministic pricing intelligence.
            </p>
          </div>

          <ShareButton />
        </div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-3 mb-16">
          <SavingsCard
            title="Monthly Savings"
            value={`$${audit.total_monthly_savings.toLocaleString()}`}
            description="Estimated monthly optimization opportunity."
          />

          <SavingsCard
            title="Annual Savings"
            value={`$${audit.total_annual_savings.toLocaleString()}`}
            description="Projected yearly savings opportunity."
          />

          <SavingsCard
            title="Optimization Score"
            value={`${optimizationScore}%`}
            description="Estimated AI stack efficiency improvement potential."
          />
        </div>

        <div className="mb-16">
          <AuditSummary
            summary={audit.summary || "This audit report identifies AI infrastructure optimization opportunities based on pricing intelligence and usage efficiency analysis. Review the recommendations below to reduce your AI infrastructure spending."}
          />
        </div>

        <div className="mb-16">
          <SavingsChart
            currentSpend={audit.total_monthly_spend}
            optimizedSpend={optimizedSpend}
          />
        </div>

        <div className="mb-12">
          <p className="text-sm font-semibold uppercase tracking-widest text-blue-400">
            Recommendations
          </p>

          <h2 className="mt-4 text-4xl font-bold tracking-tight text-white">
            Optimization Opportunities
          </h2>
        </div>

        <div className="space-y-6 pb-20">
          {audit.recommendations && Array.isArray(audit.recommendations) && audit.recommendations.length > 0 ? (
            audit.recommendations.map(
              (recommendation: any, index: number) => (
                <RecommendationCard
                  key={index}
                  tool={recommendation.tool}
                  currentPlan={recommendation.currentPlan}
                  recommendedPlan={recommendation.recommendedPlan}
                  monthlySavings={recommendation.monthlySavings}
                  annualSavings={recommendation.annualSavings}
                  confidence={recommendation.confidence}
                  reason={recommendation.reason}
                />
              )
            )
          ) : (
            <div className="rounded-2xl border border-white/10 bg-linear-to-br from-white/8 to-white/2 p-8">
              <p className="text-zinc-300">
                No optimization recommendations available for this audit.
              </p>
            </div>
          )}
        </div>

        <div className="border-t border-white/10 pt-12 pb-12 mt-12">
          <p className="text-sm text-zinc-400 text-center">
            This is a shared audit report. To run your own audit, visit{" "}
            <a href="/" className="text-blue-400 hover:text-blue-300 transition">
              Yukthi
            </a>
          </p>
        </div>
      </section>
    </main>
  );
}