import SavingsCard from "@/components/audit/savings-card";

import RecommendationCard from "@/components/audit/recommendation-card";

import SavingsChart from "@/components/charts/savings-chart";

import AuditSummary from "@/components/audit/audit-summary";
import ShareButton from "@/components/audit/share-button";
interface AuditPageProps {
  params: {
    id: string;
  };
}

async function getAudit(id: string) {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_APP_URL}/api/share?id=${id}`,
    {
      cache: "no-store",
    }
  );

  if (!response.ok) {
    return null;
  }

  return response.json();
}

export async function generateMetadata({
  params,
}: AuditPageProps) {

  const data = await getAudit(params.id);

  if (!data?.success) {
    return {
      title: "Audit Not Found",
    };
  }

  const audit = data.audit;

  return {
    title: `Save $${audit.total_annual_savings}/year on AI tools`,

    description:
      "AI infrastructure optimization report generated by AI Spend Audit.",

    openGraph: {
      title: `Save $${audit.total_annual_savings}/year on AI tools`,

      description:
        "AI infrastructure optimization report.",

      type: "website",
    },
  };
}

export default async function AuditPage({
  params,
}: AuditPageProps) {
  const data = await getAudit(params.id);

  if (!data?.success) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-black text-white">
        <p className="text-zinc-400">
          Audit report not found.
        </p>
      </main>
    );
  }

  const audit = data.audit;

  const optimizedSpend =
    audit.total_monthly_spend -
    audit.total_monthly_savings;

  const optimizationScore = Math.max(
    0,
    Math.min(
      100,
      Math.round(
        (audit.total_monthly_savings /
          audit.total_monthly_spend) *
          100
      )
    )
  );

  return (
    <main className="min-h-screen bg-black text-white">
      <section className="mx-auto max-w-7xl px-6 py-20">
        <div className="flex items-start justify-between gap-6">
          <div>
            <p className="text-sm uppercase tracking-widest text-blue-400">
              Public Audit Report
            </p>

            <h1 className="mt-4 text-5xl font-bold tracking-tight md:text-6xl">
              AI Spend Optimization
            </h1>

            <p className="mt-6 max-w-2xl text-lg leading-relaxed text-zinc-400">
              Public shareable AI infrastructure audit report.
            </p>
          </div>

          {/* <button
            onClick={() =>
              navigator.clipboard.writeText(
                window.location.href
              )
            }
            className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-medium text-white transition hover:bg-white/10"
          >
            Copy Share Link
          </button> */}
          <ShareButton />
        </div>

        <div className="mt-16 grid grid-cols-1 gap-6 md:grid-cols-3">
          <SavingsCard
            title="Monthly Savings"
            value={`$${audit.total_monthly_savings}`}
            description="Estimated monthly optimization opportunity."
          />

          <SavingsCard
            title="Annual Savings"
            value={`$${audit.total_annual_savings}`}
            description="Projected yearly savings opportunity."
          />

          <SavingsCard
            title="Optimization Score"
            value={`${optimizationScore}%`}
            description="Estimated AI stack efficiency improvement potential."
          />
        </div>

        <div className="mt-16">
          <AuditSummary
            summary="This audit report identifies AI infrastructure optimization opportunities based on pricing intelligence and usage efficiency analysis."
          />
        </div>

        <div className="mt-16">
          <SavingsChart
            currentSpend={
              audit.total_monthly_spend
            }
            optimizedSpend={optimizedSpend}
          />
        </div>

        <div className="mt-16">
          <div>
            <p className="text-sm uppercase tracking-widest text-blue-400">
              Recommendations
            </p>

            <h2 className="mt-3 text-4xl font-bold tracking-tight text-white">
              Optimization Opportunities
            </h2>
          </div>

          <div className="mt-10 space-y-6">
            {audit.recommendations.map(
              (
                recommendation: any,
                index: number
              ) => (
                <RecommendationCard
                  key={index}
                  tool={recommendation.tool}
                  currentPlan={
                    recommendation.currentPlan
                  }
                  recommendedPlan={
                    recommendation.recommendedPlan
                  }
                  monthlySavings={
                    recommendation.monthlySavings
                  }
                  annualSavings={
                    recommendation.annualSavings
                  }
                  confidence={
                    recommendation.confidence
                  }
                  reason={recommendation.reason}
                />
              )
            )}
          </div>
        </div>
      </section>
    </main>
  );
}